___

<a> <img src='https://www.python.org/static/img/python-logo.png' /></a>
___

# SF Salarios Ejercicio 

¡Realicemos un ejercicio rápido para que practiques tus habilidades con Pandas! ¡Usaremos el [Conjunto de datos de salarios de SF] (https://www.kaggle.com/kaggle/sf-salaries) de Kaggle! Simplemente sigue las instrucciones y completa las tareas que se describen en negrita a continuación. Las tareas se volverán cada vez más difíciles a medida que avanzas.

**Importar la libreria Pandas como pd**

In [4]:
import pandas as pd

**Leer Salaries.csv como un dataframe llamado sal**

In [5]:
sal = pd.read_csv("Salaries.csv")

**Compruebe el encabezado del DataFrame**

In [6]:
sal.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

**Utilice el método .info () para averiguar cuántas entradas hay.**

In [7]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  object
 2   JobTitle          148654 non-null  object
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB

**¿Cuál es el salario base promedio?**

In [8]:
sal['BasePay'].mean()

66325.44884050643

**¿Cuál es la mayor cantidad de pago por horas extra en el conjunto de datos?**

In [9]:
sal['OvertimePay'].max()

245131.88

**¿Cuál es el título del puesto de JOSEPH DRISCOLL? Nota: Use mayúsculas, de lo contrario puede obtener una respuesta que no coincida (también hay un Joseph Driscoll en minúsculas).**

In [10]:
sal[sal['EmployeeName'] == 'JOSEPH DRISCOLL']['JobTitle']

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

**¿Cuánto gana JOSEPH DRISCOLL (incluidos los beneficios)?**

In [11]:
sal[sal['EmployeeName'] == 'JOSEPH DRISCOLL']['TotalPayBenefits']

24    270324.91
Name: TotalPayBenefits, dtype: float64

**¿Cuál es el nombre de la persona mejor pagada (incluidos los beneficios)?**

In [19]:
sal[sal['TotalPayBenefits'] == sal['TotalPayBenefits'].max()]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN

**¿Cuál es el nombre de la persona peor pagada (incluidos los beneficios)? ¿Notas algo extraño sobre cuánto le pagan?**

In [20]:
sal[sal['TotalPayBenefits'] == sal['TotalPayBenefits'].min()]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.0,0.0,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,NaN

**¿Cuál fue el pago base promedio (promedio) de todos los empleados por año? (2011-2014)?**

In [14]:
sal_gby = sal.groupby('Year')
sal_gby['BasePay'].mean()

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

**¿Cuántos títulos de trabajo únicos hay?**

In [15]:
sal['JobTitle'].nunique()

2159

**¿Cuáles son los 5 trabajos más comunes?**

In [16]:
sal['JobTitle'].value_counts()[:5]

Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: JobTitle, dtype: int64

**¿Cuántos títulos de trabajo estuvieron representados por una sola persona en 2013? (por ejemplo, ¿títulos de trabajo con una sola aparición en 2013?)**

In [17]:
len(sal[sal['Year'] == 2013]['JobTitle'].value_counts() == 1)

1051

**¿Cuántas personas tienen la palabra Chief (Jefe) en su puesto de trabajo? (Esto es bastante complicado)**

In [48]:
son_jefes = list(filter(lambda val: val.lower().find('chief') != -1, sal['JobTitle'].values))

len(son_jefes)

627

627

**Bonificación: ¿Existe una correlación entre la longitud de la cadena del título del trabajo y el salario?**

# Buen trabajo!